for($=Array(3e4),_=[],f=u=c=k=0;
k<B[F='length'];
C=B[U='charCodeAt'](k++)-44,
u&&(u+=0|1/(48-C),C=3),
K=$[f]=~~$[f]-~~(1/C),
f+=0|1/(C-17),
C||I[F]>c&&($[f]=I[U](c++)),
C^2||O(String.fromCharCode(K)),
C^47||(K?_.push(k):u++),
C^49||(K?k=_[_[F]-1]:_.pop()));
